services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 1433:1433
    volumes:
      - db:/data/mssql
    networks:
      - bostnet

networks:
  bostnet:
    name: bostnet
    driver: bridge

volumes:
  db:
